name: Sprint Milestone

on:
  schedule:
    # Every monday at 12UTC, create the new milestone
   - cron: "0 12 * * 1"

jobs:
  sprint_milestone:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/sprint-milestone-action@v2.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        sprint-duration: 2 # Default is 1
